version: '3'

services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/zaru/go-api-documents-demo:cached
    ports:
      - "1323:1323"
    tty: yes
    depends_on:
      - db
      - kvs
  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: sample
    ports:
      - "3306:3306"
  kvs:
    image: redis
    ports:
      - "6379:6379"
volumes:
  data:
