FORMAT: 1A

# Go API ドキュメント デモ

# Group グループです

## ユーザ [/users]

### 一覧 [GET]

+ Response 200 (application/json; charset=UTF-8)

    + Attributes
      + users (array[User], fixed-type)

## Data Structures

### User
+ id: `100` (number) - User ID
+ name: `zaru` (string) - User name
+ rank: `1` (enum[number]) - User rank
  + 1
  + 2
  + 3
  + Default: 1
